### ISSUE TITLE
Development of standalone xarray merge tool

### ISSUE THREAD

**Issue by charlesbluca** [NCAR/esm-collection-spec#12]
Looking through #6, it seems like we have the knowledge and infrastructure to create a standalone xarray merging tool that could work using information provided by `aggregation_control` to merge the assets of a catalog - this could be particularly useful in moving forward with [Pangeo Forge](https://github.com/pangeo-forge/pangeo-smithy), which would seek to automate the process of data merging/uploading to cloud.

@andersy005, what luck have you had implementing `apply_aggregation` in intake-esm?

cc @matt-long

**Comment by matt-long** [comment]
`apply_aggregation` is implemented and is generally functional. During the CMIP6 Hackthon, however, we encountered several issues, most related to anomalies in the underlying data. I hope that we can sort these out over the next couple of weeks.
