### ISSUE TITLE
release and get a DOI?

### ISSUE THREAD

**Issue by rabernat** [NCAR/esm-collection-spec#18]
For the proposal I'm writing (due Thursday!) it would be nice to be able to refer to esm-collection-spec via a DOI.

@andersy005 - any chance you could set up a zenodo DOI asap?

Thanks!!!

**Comment by andersy005** [comment]
> @andersy005 - any chance you could set up a zenodo DOI asap?

Done! 
![Screen Shot 2020-03-10 at 12 44 26 PM](https://user-images.githubusercontent.com/13301940/76347864-e9961900-62cc-11ea-8b61-f332001913c6.png)

**Comment by rabernat** [comment]
You rock @andersy005!
