### ISSUE TITLE
Add spec validator script

### ISSUE THREAD

**Issue by andersy005** [NCAR/esm-collection-spec#2]
CSV: use https://github.com/di/vladiate

**Comment by rabernat** [comment]
Could probably adapt many ideas from stac validator for the json part: https://github.com/sparkgeo/stac-validator

**Comment by andersy005** [comment]
I am planning on making progress on this and #5 today, and tomorrow.

**Comment by rabernat** [comment]
FYI, I am hoping we can have something up and running by Wednesday so we can start writing the hackathon user guide.

I'm standing by to help however I can.

**Comment by rabernat** [comment]
We should also engage with @martindurant to figure out the best way to bring the qgrid-style catalog browsing into intake (as he demo'd in https://github.com/intake/intake/issues/417).

**Comment by andersy005** [comment]
@naomi-henderson 

Is `https://storage.googleapis.com/cmip6/cmip6-zarr-consolidated-stores.csv`  still the most recent cmip6 google cloud csv catalog? 


@rabernat, where should we store the actual CMIP6 Google Cloud collection (json file)? 

For CMIP6 on Glade, we've been granted permission to `glade/collections/cmip/catalog` and I am planning on setting up a cron-job to update the (csv) catalog over night. 

Cc @matt-long

**Comment by naomi-henderson** [comment]
Yes, @andersy005 , that is the csv catalog file that reflects our current collection.  The column with the path to the zarr store is still called `zstore` rather than `path` - do we still want to change it?

**Comment by andersy005** [comment]
> do we still want to change it?

With the new esm-collection-spec, we don't need to change it.  We will use it as is by specifying column_name to be `zstore` in the collection-spec file.

**Comment by andersy005** [comment]
Implemented in #9. Needs improvements though ( I will look into this in a separate PR)
