### ISSUE TITLE
How can aggregation control be optional ?

### ISSUE THREAD

**Issue by aulemahal** [NCAR/esm-collection-spec#35]
Hi,

In `intake-esm` PR's intake/intake-esm#551, the model was updated mirror what this spec says : `aggregation_control` is an optional field of the catalog spec.

However, this doesn't work. I have tested opening a catalog with the new intake-esm and it fails. I will open an issue there about this, but first I wanted to understand how `aggegation control` could infact be optional.

In intake-esm, the `ESMDataSource` object requires a `variable_column_name`, which is taken in `esmcat.aggregation_control.variable_column_name`. I don't see how the whole mechanic could work without a variable name at the opening step. However, if `aggregation_control` is optional, thus this column name also is optional. 

If `intake-esm` is the official implementation of this spec and cannot work without the  `aggregation_control` field, I'm guessing then that the spec is wrong and the file indeed is required.

**Comment by andersy005** [comment]
thank you for opening this issue, @aulemahal. do you mind opening this issue upstream in intake/intake-esm?

 i moved the spec there: https://github.com/intake/intake-esm/blob/main/docs/source/reference/esm-catalog-spec.md and forgot to archive this repo :)

**Comment by aulemahal** [comment]
Oh! I see! I'll move this over.
